### PR TITLE
Added no_std support

### PR DESCRIPTION
**Pull request by emoon**
This adds `no_std` support to the crate. By default `std` is enabled.

### CODE REVIEW

**Review by Mathys-Gasnier — CHANGES_REQUESTED** [review]
Could you check it's still not using std after the merge of my PR ?

**Comment by emoon** [comment]
I have merged with your changes now

**Comment by Mathys-Gasnier** [comment]
You're missing `custom.rs` which has a use of std that could be replaced to core

**Comment by emoon** [comment]
Ah, I will fix.

**Review by Mathys-Gasnier — APPROVED** [review]

**Comment by emoon** [comment]
Should all be fixed up now

**Pull request merged**
